const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUx4MW5QeGtWL1ZZdk1Ca2dVazNVQmFIV1FONHppK2U4NTJqR2FPT3htND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMHBOZmxLQ2FXYkRvemltR2Flc0F6QUdDaEUrdHJ5SFpUSkdlcXFaak1Gdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0SVZxMjZHbER5aUNVL25nenp2Q1QvT05Kand6MHBtS1B5dDZTRC9ibVgwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJaEQ2QWhXTG80LzBOaE1wOXZWSEgwZWpOWDFRSXlCOFBTVGY0N2hQZFRzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndMOGRqVkR4aHdFTlNKL3g4dVFQZzd0eTRNRzA3c1FUR3ZDTDdRanM0R2M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVHb09qR0x4T3hyekpSNlNLUThTUHVvYTFhNlgvVnA3MVJ0UDc5SmhNaDQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUU04L1o3OCtnbFI3S2dubEM3Q00wSDlnYjZOeUtBVGtpSzEzYTM3TmhrOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicmJXYkJBd1ZDRHlBT3EzTE1tZFcxV0N1WFBnWVJDemNNRWNUcWMrcWhYWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVFZXlrakhicGRaNWtEa3hCeURlSzV3aGlGaHZsVjBZQzZ1dlIxNkxHeFdFZW51SUFhbzNjUHN6R1RIdDA1dUhTYkdnb0FCYmZEK1pTby9iRlV1akJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODYsImFkdlNlY3JldEtleSI6Im1UeEFNbXRJREhOT1lqQUlxdHFHY1BwRSsyRkFOaU10RDRlNVg2bVVwTTQ9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjJMMVAzTFdWIiwibWUiOnsiaWQiOiIyMzQ3MDI2MTM4Mzg0OjUzQHMud2hhdHNhcHAubmV0IiwibGlkIjoiMTg0MzIzMTUyMDgwOTUxOjUzQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUHFSMTlRR0VMN3I4N3dHR0FZZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoibjcvaDZkaDBqSkVnTGtJWkVKQjQydzk4Q3R1cUdNSEo1UTJzOXFTN2tqUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiTi9SeFNJTXp0b2VBRFZaM0JUWHl5TTlveTFJcWNMZTNEaFZKbk83ODE0TU9zOEd3NVdVeUVzVnJtZG9vS1BHc0pKeTJqRFdjY0VLek8yZ20wdEQ4Q0E9PSIsImRldmljZVNpZ25hdHVyZSI6IjYxL3lHbjJhZDAySUlyUjF2cEhvNUpvZWZOODB6NnJKVjE3TkhuWWpqajZnYy94TE42WnhOM2RRVWk5bVNEVTVteDlkc3ZobS9HRXdzc2xKQldqOUJnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0NzAyNjEzODM4NDo1M0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJaKy80ZW5ZZEl5UklDNUNHUkNRZU5zUGZBcmJxaGpCeWVVTnJQYWt1NUkwIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQlE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzgzMzk3ODcsImxhc3RQcm9wSGFzaCI6IjJHNEFtdSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSTl4In0=",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
